### ISSUE TITLE
Libfunc completion tracking list.

### ISSUE THREAD

**Issue by azteca1998** [lambdaclass/cairo_native#221]
Total: 177 libfuncs
  - 91 implemented (in the current refactor, there are more we haven't ported from the pre-refactor branch yet).
  - of which 14 of them are either incomplete, placeholders or we aren't sure they are implemented correctly.

  - [ ] `alloc_local`
  - [x] `array_append`
  - [x] `array_get`
  - [x] `array_len`
  - [x] `array_new`
  - [x] `array_pop_front_consume`
  - [x] `array_pop_front`
  - [ ] `array_slice`
  - [x] `array_snapshot_pop_back`
  - [x] `array_snapshot_pop_front`
  - [ ] `bitwise`
  - [x] `bool_and_impl`
  - [x] `bool_not_impl`
  - [x] `bool_or_impl`
  - [ ] `bool_to_felt252`
  - [x] `bool_xor_impl`
  - [x] `branch_align`
  - [ ] `call_contract_syscall` (StarkNet)
  - [ ] `class_hash_const` (StarkNet)
  - [ ] `class_hash_to_felt252` (StarkNet)
  - [ ] `class_hash_try_from_felt252` (StarkNet)
  - [ ] `contract_address_const` (StarkNet)
  - [ ] `contract_address_to_felt252` (StarkNet)
  - [ ] `contract_address_try_from_felt252` (StarkNet)
  - [ ] `deploy_syscall` (StarkNet)
  - [x] `disable_ap_tracking`
  - [ ] `downcast`
  - [3] `drop`
  - [3] `dup`
  - [ ] `ec_neg`
  - [ ] `ec_point_from_x_nz`
  - [ ] `ec_point_is_zero`
  - [ ] `ec_point_try_new_nz`
  - [ ] `ec_point_unwrap`
  - [ ] `ec_point_zero`
  - [ ] `ec_state_add_mul`
  - [ ] `ec_state_add`
  - [ ] `ec_state_init`
  - [ ] `ec_state_try_finalize_nz`
  - [ ] `emit_event_syscall` (StarkNet)
  - [x] `enable_ap_tracking`
  - [x] `enum_init`
  - [x] `enum_match`
  - [ ] `enum_snapshot_match`
  - [4] `felt252_add_const`
  - [x] `felt252_add`
  - [x] `felt252_const`
  - [ ] `felt252_dict_entry_finalize`
  - [ ] `felt252_dict_entry_get`
  - [ ] `felt252_dict_new`
  - [ ] `felt252_dict_squash`
  - [4] `felt252_div_const`
  - [4] `felt252_div`
  - [x] `felt252_is_zero`
  - [4] `felt252_mul_const`
  - [x] `felt252_mul`
  - [4] `felt252_sub_const`
  - [x] `felt252_sub`
  - [ ] `finalize_locals`
  - [x] `function_call`
  - [ ] `get_available_gas`
  - [ ] `get_block_hash_syscall` (StarkNet)
  - [5] `get_builtin_costs`
  - [ ] `get_execution_info_syscall` (StarkNet)
  - [2] `into_box`
  - [x] `jump`
  - [ ] `keccak_syscall` (StarkNet)
  - [ ] `library_call_syscall` (StarkNet)
  - [ ] `match_nullable`
  - [ ] `null`
  - [ ] `nullable_from_box`
  - [x] `pedersen`
  - [ ] `pop_log` (StarkNet, testing)
  - [ ] `poseidon`
  - [x] `print`
  - [ ] `redeposit_gas`
  - [x] `rename`
  - [ ] `replace_class_syscall` (StarkNet)
  - [1] `revoke_ap_tracking`
  - [ ] `secp256k1_add_syscall` (StarkNet)
  - [ ] `secp256k1_get_point_from_x_syscall` (StarkNet)
  - [ ] `secp256k1_get_xy_syscall` (StarkNet)
  - [ ] `secp256k1_mul_syscall` (StarkNet)
  - [ ] `secp256k1_new_syscall` (StarkNet)
  - [ ] `secp256r1_add_syscall` (StarkNet)
  - [ ] `secp256r1_get_point_from_x_syscall` (StarkNet)
  - [ ] `secp256r1_get_xy_syscall` (StarkNet)
  - [ ] `secp256r1_mul_syscall` (StarkNet)
  - [ ] `secp256r1_new_syscall` (StarkNet)
  - [ ] `send_message_to_l1_syscall` (StarkNet)
  - [ ] `set_account_contract_address` (StarkNet, testing)
  - [ ] `set_block_number` (StarkNet, testing)
  - [ ] `set_block_timestamp` (StarkNet, testing)
  - [ ] `set_caller_address` (StarkNet, testing)
  - [ ] `set_chain_id` (StarkNet, testing)
  - [ ] `set_contract_address` (StarkNet, testing)
  - [ ] `set_max_fee` (StarkNet, testing)
  - [ ] `set_nonce` (StarkNet, testing)
  - [ ] `set_sequencer_address` (StarkNet, testing)
  - [ ] `set_signature` (StarkNet, testing)
  - [ ] `set_transaction_hash` (StarkNet, testing)
  - [ ] `set_version` (StarkNet, testing)
  - [6] `snapshot_take`
  - [x] `storage_address_from_base_and_offset` (StarkNet)
  - [x] `storage_address_from_base` (StarkNet)
  - [x] `storage_address_to_felt252` (StarkNet)
  - [x] `storage_address_try_from_felt252` (StarkNet)
  - [x] `storage_base_address_const` (StarkNet)
  - [x] `storage_base_address_from_felt252` (StarkNet)
  - [ ] `storage_read_syscall` (StarkNet)
  - [ ] `storage_write_syscall` (StarkNet)
  - [ ] `store_local`
  - [x] `store_temp`
  - [x] `struct_construct`
  - [x] `struct_deconstruct`
  - [ ] `struct_snapshot_deconstruct`
  - [x] `u128_byte_reverse`
  - [x] `u128_const`
  - [x] `u128_eq`
  - [ ] `u128_guarantee_mul`
  - [x] `u128_is_zero`
  - [ ] `u128_mul_guarantee_verify`
  - [x] `u128_overflowing_add`
  - [x] `u128_overflowing_sub`
  - [x] `u128_safe_divmod`
  - [ ] `u128_sqrt`
  - [x] `u128_to_felt252`
  - [x] `u128s_from_felt252`
  - [x] `u16_const`
  - [x] `u16_eq`
  - [x] `u16_is_zero`
  - [x] `u16_overflowing_add`
  - [x] `u16_overflowing_sub`
  - [x] `u16_safe_divmod`
  - [ ] `u16_sqrt`
  - [x] `u16_to_felt252`
  - [x] `u16_try_from_felt252`
  - [ ] `u16_wide_mul`
  - [ ] `u256_is_zero`
  - [ ] `u256_safe_divmod`
  - [ ] `u256_sqrt`
  - [x] `u32_const`
  - [x] `u32_eq`
  - [x] `u32_is_zero`
  - [x] `u32_overflowing_add`
  - [x] `u32_overflowing_sub`
  - [x] `u32_safe_divmod`
  - [ ] `u32_sqrt`
  - [x] `u32_to_felt252`
  - [x] `u32_try_from_felt252`
  - [ ] `u32_wide_mul`
  - [ ] `u512_safe_divmod_by_u256`
  - [x] `u64_const`
  - [x] `u64_eq`
  - [x] `u64_is_zero`
  - [x] `u64_overflowing_add`
  - [x] `u64_overflowing_sub`
  - [x] `u64_safe_divmod`
  - [ ] `u64_sqrt`
  - [x] `u64_to_felt252`
  - [x] `u64_try_from_felt252`
  - [ ] `u64_wide_mul`
  - [x] `u8_const`
  - [x] `u8_eq`
  - [x] `u8_is_zero`
  - [x] `u8_overflowing_add`
  - [x] `u8_overflowing_sub`
  - [x] `u8_safe_divmod`
  - [ ] `u8_sqrt`
  - [x] `u8_to_felt252`
  - [x] `u8_try_from_felt252`
  - [ ] `u8_wide_mul`
  - [2] `unbox`
  - [ ] `unwrap_non_zero`
  - [ ] `upcast`
  - [5] `withdraw_gas_all`
  - [5] `withdraw_gas`

[1]: It is implemented but we're not sure if it has some stuff we don't know of.
[2]: It is implemented but we're still debating whether it should be a Rust-like `Box<T>` or if it's
    fine treating it like another variable.
[3]: It is implemented but side-effects are not yet handled (ex. array cloning/dropping).
[4]: Not supported by the Cairo to Sierra compiler.
[5]: Implemented with a dummy. It doesn't do anything yet.
[6]: It is implemented but we're not handling potential issues like lifetimes yet.

**Comment by igaray** [comment]
Closing this tracking issue as it has become stale and progress has been tracked elsewhere.
