### ISSUE TITLE
Libfuncs: snapshot

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#93]
- [snapshot](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/snapshot.rs)
  - [x] snapshot_take (done in #79)
- [structure](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/structure.rs) 
  - [x] struct_snapshot_deconstruct #369 
- [array](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/array.rs)
  - [x] array_snapshot_pop_front
- [enm](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/enm.rs)
  - [x] enum_snapshot_match #366
