### ISSUE TITLE
Tracking issue: starknet interoperability libfuncs

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_native#98]
Some of the following libfuncs may warrant their own issue:

- [Sierra implementation](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/starknet/interoperability.rs)
  - [x] contract_address_const
  - [x] contract_address_to_felt252
  - [x] contract_address_try_from_felt252
  - [ ] class_hash_const
  - [x] class_hash_to_felt252
  - [x] class_hash_try_from_felt252
  - [x] call_contract_syscall
  - [x] deploy_syscall
  - [x] library_call_syscall
  - [x] send_message_to_l1_syscall
